### ISSUE TITLE
[XBMCBOT] - SSLError: [Errno 1] _ssl.c:480: error:14094067:SSL routines:SSL3_READ_BYTES:bad change cipher spec

### ISSUE THREAD

**Issue by xbmcbot** [aussieaddons/plugin.video.netball-live#227]
*Automatic bug report from end-user.*
## Environment
**Add-on Name:** Netball Live
**Add-on ID:** plugin.video.netball-live
**Add-on Version:** 1.0.0
**Kodi Version:** 15.2 Git:2015-10-19-02e7013
**Python Version:** 2.6.5 (r265:79063, Oct 19 2015, 08:05:00) [GCC 4.8]
**Operating System:** linux3  (Linux 3.4.0-6004186 armv7l)
**IP Address:** 160.178.153.180 (sagembox)
**ISP:** Office National des Postes et Telecommunications O
**Kodi URL:** ?action=listmatches&dummy=None&thumb=None&title=[COLOR green][LIVE NOW][/COLOR] NSW Swifts v West Coast Fever [COLOR yellow]50 - 48[/COLOR]&video_id=9ycHcyYjE6Mj9BNGqi5-bbXACsH284M5&live=true&time=None&desc=None
**Python Path:**
```
/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netball-live
/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.common.plugin.cache/lib
/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.beautifulsoup4/lib
/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib
/
/data/app/org.xbmc.kodi-1.apk/assets/python2.6/lib/python26.zip
/data/app/org.xbmc.kodi-1.apk/assets/python2.6/lib/python2.6
/data/app/org.xbmc.kodi-1.apk/assets/python2.6/lib/python2.6/plat-linux3
/data/app/org.xbmc.kodi-1.apk/assets/python2.6/lib/python2.6/lib-tk
/data/app/org.xbmc.kodi-1.apk/assets/python2.6/lib/python2.6/lib-old
/data/app/org.xbmc.kodi-1.apk/assets/python2.6/lib/python2.6/lib-dynload
/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netball-live/resources/lib
```

## Traceback
```
Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netball-live/resources/lib/play.py", line 39, in play_video
    playlist = ooyalahelper.get_m3u8_playlist(video_id, live)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netball-live/resources/lib/ooyalahelper.py", line 164, in get_m3u8_playlist
    login_token = get_user_ticket()
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netball-live/resources/lib/ooyalahelper.py", line 69, in get_user_ticket
    ticket = telstra_auth.get_free_token(username, password)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.netball-live/resources/lib/telstra_auth.py", line 89, in get_free_token
    signon = session.post(config.SIGNON_URL, data=signon_data)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:480: error:14094067:SSL routines:SSL3_READ_BYTES:bad change cipher spec

```

[Full log](https://gist.github.com/1927ad31487382a20abbe4b2e39b4dfc)
